# coding: utf-8


class ANNOTATION_TYPE: pass
class ANNOTATION_TYPE_TEXT(ANNOTATION_TYPE): pass
class ANNOTATION_TYPE_SOUND(ANNOTATION_TYPE): pass
class ANNOTATION_TYPE_SPEAK(ANNOTATION_TYPE): pass
class ANNOTATION_TYPE_ICON(ANNOTATION_TYPE): pass


class REMINDING_TIME: pass
class REMINDING_TIME_30SEC(REMINDING_TIME): pass
class REMINDING_TIME_2MIN(REMINDING_TIME): pass
class REMINDING_TIME_5MIN(REMINDING_TIME): pass